Tasteplace/urls.py
from django.contrib import admin
from django.urls import path, include
from food import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name="index"),
    path('food/',include('food.urls',namespace='food')),
    
]


food/urls.py
from django.urls import path

from . import views

app_name='food'

urlpatterns= [
    path('pizza',views.pizza, name='pizza'),
    path('Burger',views.Burger, name='Burger'),
    path('order',views.order, name='order'),
    path('success',views.success, name='success'),
    path('signup',views.signup, name='signup'),
    path('login',views.logIn, name='login'),
    path('logout',views.logOut, name='logout'),

]

food/models.py
from django.db import models
from django.contrib.auth.models import  User

# Create your models here.
class pizza(models.Model):
    name = models.CharField(max_length=120)
    priceM = models.IntegerField()
    priceL= models.IntegerField()
    pImage= models.URLField()
    
    
class Burger(models.Model):
    name = models.CharField(max_length=120)
    priceM = models.IntegerField()
    priceL= models.IntegerField()
    bImage= models.URLField()
    
class Order(models.Model):
    customer=models.ForeignKey(User, on_delete=models.CASCADE)
    number=models.CharField(max_length=60)
    bill=models.IntegerField()
    date= models.DateTimeField(auto_now_add=True, blank=True)
    note=models.TextField(blank=True, null=True)
    
class Item(models.Model):
    order=models.ForeignKey(Order, on_delete=models.CASCADE)
    name=models.CharField(max_length=120)
    price = models.IntegerField()
    size=models.CharField(max_length=60)
    
    
    
    


food/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    class Meta:
        email = forms.EmailField(max_length=100, required=True,help_text="Informs a valid email address")
        model=User
        fields=['username','email','password1','password2']

food/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import pizza as p, Burger as b, Order , Item
from .forms import NewUserForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
import random
import json

def randomOrderNumber(length):
    sample='ABCDEFGH0123456789'
    number0=''.join((random.choice(sample) for i in range(length)))
    return number0

# Create your views here.
def index(request):
    request.session.set_expiry(0)
    ctx= {'active_link':'index'}
    return render(request,'food/index.html',ctx)

def pizza(request):
    request.session.set_expiry(0)
    pizzas= p.objects.all()
    ctx= {'pizzas':pizzas,'active_link':'pizza'}
    return render(request, 'food/pizza.html',ctx)

def Burger(request):
    request.session.set_expiry(0)
    burgers= b.objects.all()
    ctx= {'burgers':burgers, 'active_link':'Burger'}
    return render(request, 'food/burger.html',ctx)


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

@csrf_exempt
def order(request):
    request.session.set_expiry(0)
    bill=0.0   
    if is_ajax(request=request):
        request.session['note'] = request.POST.get('note')
        request.session['order'] = request.POST.get('orders')
        request.session['bill'] = request.POST.get('bill')

        orders = json.loads(request.session['order'])
        randomNum = randomOrderNumber(6)

        while Order.objects.filter(number=randomNum).count() > 0:
            randomNum = randomOrderNumber(6)

        if request.user.is_authenticated:
            # bill = bill if request.session['bill'] else 0.0
            bill_str = request.session.get('bill', '0.0')  # default to '0.0' if 'bill' is not present
            if bill_str is not None:
                bill = float(bill_str)
            order = Order(customer=request.user, number=randomNum, bill=bill, note=request.session['note'])
            order.save()
            request.session['orderNum'] = order.number
            request.session['bill'] = bill
            for article in orders:
                item = Item(order=order, name=article['name'], price=article['price'], size=article['size'])
                item.save()

    ctx = {'active_link': 'order'}
    return render(request, 'food/order.html', ctx)

def success(request):
    orderNum=  request.session.get('orderNum','')
    bill= request.session.get('bill',0.0)
    items=Item.objects.filter(order__number=orderNum)
    # order = request.session.get('order')
    ctx={'orderNum':orderNum,'bill':bill, 'items':items}
    return render(request, 'food/success.html', ctx)

def signup(request):
    ctx={}
    if request.POST:
        form= NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            ctx['form']=form
    else:
        form= NewUserForm()
        ctx['form']=form
    return render(request, 'food/signup.html', ctx)

def logIn(request):
    if request.POST:
        username=request.POST.get('username')
        pwd=request.POST.get('password')
        user= authenticate(username=username, password=pwd)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.info(request,'username and/or password are incorrect')
            
    ctx={'active_link':'login'}
    return render(request, 'food/login.html', ctx)

def logOut(request):
    logout(request)
    return redirect('index')
    

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{% block title%}{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <link rel="stylesheet" type="text/css" href="{% static 'food/css/style.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="#">
                <img src="https://cdn-icons-png.flaticon.com/512/2771/2771401.png" class="logo">
            </a>
            
            <!-- Links -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mynav" aria-controls="mynav">
          <span class="navbar-toggler-icon" ></span>
        </button>
        <div class="collapse navbar-collapse" id="mynav">  
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link {% if active_link == 'index' %} active{%endif%}" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if active_link == 'pizza' %} active{%endif%}" href="{% url 'food:pizza' %}">pizza</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if active_link == 'Burger' %} active{%endif%} " href="{%url 'food:Burger' %}">Burger</a>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto" >
              {% if user.is_authenticated %}
              <li class="nav-item mt-2">
                <h5 class="text-light pt-3 pr-4">Welcome {{user.username}}!!!</h5>
                
              </li>
              {% endif %}
              <li class="nav-item mt-2">
                <a class="nav-link {% if active_link == 'order' %} active{%endif%} " href="{%url 'food:order' %}"><img class="cart-img" src="https://cdn-icons-png.flaticon.com/512/263/263142.png"><span id="cart"></span></a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link {% if active_link == 'login' %} active{%endif%} " href="{%url 'food:logout' %}">
                  <img class="proflie-img" src="https://cdn-icons-png.flaticon.com/512/3106/3106773.png">Log Out</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link {% if active_link == 'login' %} active{%endif%} " href="{%url 'food:login' %}">
                  <img class="proflie-img" src="https://cdn-icons-png.flaticon.com/512/3106/3106773.png">Login</a>
              </li>
              {% endif %}
            </ul>
          </nav>
        </div>
            {% block content %}
            <h2 id="heading">Welcome To The Tasteplace</h2>
            {% endblock %}
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'food/js/main.js'%}"></script>
        
    </body>
    </html>

food/templates/food/burger.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %}Burger{% endblock %}



{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h2 class="title"> Our Burgers</h2>
            <div class="row">
            {% for burger in burgers %}
            <div class="col-md-4 p-4">
                <img class="picture" src="{{burger.bImage}}">
                <h4 class="pt-3" id="burger{{burger.id}}">{{burger.name}}</h4>
                <div class="form-check-inline">
                    <label class="form-check-label">
                        <input class="form-check-input" type="radio" name="burger{{burger.id}}"  value="{{burger.priceM}}" checked>
                        M:  Rs. {{burger.priceM}}
                    </label>
                </div>
                <div class="form-check-inline">
                    <label class="form-check-label">
                        <input class="form-check-input" type="radio" name="burger{{burger.id}}"  value="{{burger.priceL}}">
                        L:  Rs. {{burger.priceL}}
                    </label>
                </div>
                <div class="form-check">
                <button class="btn-info mt-3" onclick="addBurger('{{burger.id}}')" >Add To Cart</button>
                </div>
            </div>
            {% endfor %}
            </div> 
        </div>
        <div class="col-md-4 orders">   
            <div class="bg-dark p-4 rounded text-light">
            <h2 class="text-center">Order List</h2>
                <ul id="bcart"></ul>
                <h4 class="text-right" id="btotal">Total: Rs. 0</h4>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'food/js/borders.js'%}"></script>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="home">
    
</div> 

{% endblock %}

food/templates/food/login.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %}Login{% endblock %}

{% block content %}
    <div class="container-fluid p-5">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6 p-4 bg-dark text-light text-center " id="box-body">
                <h3 class="text-center">Log In</h3>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">                     
                        <input type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">                     
                        <input type="password" name="password" placeholder="Password">
                    </div>
                    <button type="submit" class="btn-info">Log In</button><br>
                    <a href="{% url 'food:signup' %}" class="pt-10">Sign Up</a>
                    {% if messages %}
                        <ul class="pt-2 text-center" >
                            {% for msg in messages %}
                            <li style="color:red">{{ msg }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>

    </div>

{% endblock %}

food/templates/food/order.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %}Order{% endblock %}



{% block content %}
    <div class="container-fluid m-4">
        {% if user.is_authenticated %}
            <h2>Welcome {{user.username}}</h2>
        {% endif %}
        <div class="row">
            <div class="col-md-6 mt-10 text-center">
                <h2>Order</h2>
                <div class="row">
                    <div class="col-md-3" id="name">
                        <h3>Name</h3>
                    </div>
                    <div class="col-md-3" id="size">
                        {% comment %} <h3>Size</h3> {% endcomment %}
                    </div>
                    <div class="col-md-3" id="price">
                        <h3>Price</h3>
                    </div>
                    <div class="col-md-1" id="rm">
                        
                    </div>
                </div>
                <h2 id="total" >Total: </h2>     
            </div>

            <div class="col-md-5 mt-4">
                <h2>Message</h2>
                <textarea name="message" id="message" rows="5" cols="40"></textarea>
                {% if user.is_authenticated %}
                <div class="ml-auto m-4">
                    <button type="submit" class="btn-success" onclick="submitorders()"> Submit </button>
                </div>
                {% else %}
                <div class="ml-auto m-4">
                    <a href="{% url 'food:login' %}">Log In</a>
                </div>
                {% endif %}
                
            </div>
        </div>
    </div>
    <script src="{% static 'food/js/cart.js'%}"></script>
{% endblock %}

food/templates/food/pizza.html
{% extends 'food/base.html' %}
{% load static %}

{% block title %}Pizza{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            
            <div class="col-md-12 text-center">
                <h2 class="title"> Our Pizzas</h2>
                <div class="row">
                {% for pizza in pizzas %}
                <div class="col-md-4 p-4">
                    <img class="picture" src="{{pizza.pImage}}">
                    <h4 class="pt-3" id="pizza{{pizza.id}}">{{pizza.name}}</h4>
                    <div class="form-check-inline">
                        <label class="form-check-label">
                            <input class="form-check-input" type="radio" name="pizza{{pizza.id}}"  value="{{pizza.priceM}}" checked>
                            M:  Rs. {{pizza.priceM}}
                        </label>
                    </div> 
                    <div class="form-check-inline">
                        <label class="form-check-label">
                            <input class="form-check-input" type="radio" name="pizza{{pizza.id}}"  value="{{pizza.priceL}}">
                            L:  Rs. {{pizza.priceL}}
                        </label>
                    </div>
                    <div class="form-check">
                    <button class="btn-info mt-3" onclick="addPizza('{{pizza.id}}')">Add To Cart</button>
                    </div>
                </div>
                {% endfor %}
                </div> 
            </div>
            <div class="col-md-4 orders">   
                <div class="bg-dark p-4 rounded text-light">
                    <h2 class="text-center">Order List</h2>
                    <ul id="pcart"></ul>
                    <h4 class="text-right" id="ptotal">Total: Rs. 0</h4>
                </div>

            </div>
        </div>
    </div>
    <script src="{% static 'food/js/order.js'%}"></script>
{% endblock %} 

food/templates/food/signup.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %}SignUp{% endblock %}

{% block content %}
    <div class="container-fluid p-5">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6 p-4 bg-dark text-light text-center " id="box-body">
                <h3 class="text-center">SignUp</h3>
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <div>
                            {{field.label_tag}}
                        </div>
                        <div>
                            {{ field }}
                        </div>
                        {%if field.help_text%}
                        <small style="color:grey">{{field.help_text}}</small>

                        {%endif%}
                        
                    </div>
                    {% endfor %}
                    {% for error in form.errors %}

                        <small style="color:red">{{error}}</small>
                        {% endfor%}
                    <button class="btn-info md-5" type="submit" >SignUp</button><br>
                    <a href="{% url 'food:signup' %}" >Log In</a>
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>

    </div>

{% endblock %}

food/templates/food/success.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %}Success{% endblock %}

{% block content %}
    <div class="container-fluid">
        <h2>We have received your order </h2>
        <h4>Number of order: {{ orderNum }}</h4>
        <h4>You have ordered: </h4>
        {% for item in items %}
        <h3>{{item.name}}{{item.size}}{{item.price}}</h3>
        {% endfor %}
        <h4>Total: Rs. {{bill}} </h4>
        <h4>If you want to modify your order, please call us</h4>
        <h4>Phone: 00 65 78 34 45</h4>
    </div>
{% endblock %}